#!/bin/bash
set -e

if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This script must be run as root" >&2
    exit 1
fi

echo "=== simple-login-gui installer ==="
echo

# ── X server selection ───────────────────────────────────────────────────────
echo "Which X server are you using?"
echo "  1) XLibre (recommended for Devuan Excalibur)"
echo "  2) Xorg"
echo
while true; do
    read -p "Enter number [1-2]: " XSERVER_CHOICE
    case "$XSERVER_CHOICE" in
        1|2) break ;;
        *) echo "  Invalid choice. Enter 1 or 2." ;;
    esac
done

if [ "$XSERVER_CHOICE" = "1" ]; then
    if command -v Xlibre > /dev/null 2>&1; then
        echo "  Found: Xlibre at $(command -v Xlibre)"
    elif command -v Xorg > /dev/null 2>&1; then
        echo "  Note: Xlibre binary not found in PATH."
        echo "  XLibre may be installed as 'Xorg' on some systems (it replaces xorg-server)."
        echo "  Found: Xorg at $(command -v Xorg) — this will be used as the X server."
    else
        echo
        echo "  WARNING: No X server binary found."
        echo "  Install XLibre from the Devuan XLibre repository before rebooting."
        echo "  Installation will continue but the login screen will not work"
        echo "  until an X server is installed."
    fi
else
    if command -v Xorg > /dev/null 2>&1; then
        echo "  Found: Xorg at $(command -v Xorg)"
    else
        echo
        echo "  WARNING: Xorg not found. Install it before rebooting."
    fi
fi
echo

# ── GTK version selection ─────────────────────────────────────────────────────
echo "Which GTK version would you like to use?"
echo "  1) GTK3 (recommended)"
echo "  2) GTK2"
echo
while true; do
    read -p "Enter number [1-2]: " GTK_CHOICE
    case "$GTK_CHOICE" in
        1) GTK_VERSION=3; GTK_RT_PKG="libgtk-3-0";  GTK_DEV_PKG="libgtk-3-dev";  break ;;
        2) GTK_VERSION=2; GTK_RT_PKG="libgtk2.0-0"; GTK_DEV_PKG="libgtk2.0-dev"; break ;;
        *) echo "  Invalid choice." ;;
    esac
done
echo "  Using GTK${GTK_VERSION}."
echo

# ── GPU detection: configure seatd integration ────────────────────────────────
echo "Detecting GPU driver..."
XSERVER_FLAGS="-seat seat0 -keeptty -nolisten tcp -ac"

if lsmod 2>/dev/null | grep -q '^nvidia '; then
    echo "  NVIDIA proprietary driver detected."
    echo "  The nvidia DDX driver does not support libseat device management."
    echo "  seatd integration will be disabled for the X server."
    echo "  seatd will still run and is available for Wayland compositors."
    XSERVER_FLAGS="-nolisten tcp -ac"
else
    echo "  Open-source GPU driver detected. Full seatd integration enabled."
fi
echo

cat > /etc/xlogin.conf <<EOF
# xlogin configuration -- generated by install.sh
# XSERVER_FLAGS are passed to the X server by xlogin-launcher at startup.
# seatd integration (-seat seat0 -keeptty) requires an open-source GPU driver.
# The nvidia proprietary DDX driver does not support libseat device management.
XSERVER_FLAGS="$XSERVER_FLAGS"
EOF
echo "  Wrote /etc/xlogin.conf"
echo

# ── Runtime dependencies ──────────────────────────────────────────────────────
echo "Installing runtime dependencies..."
apt-get update -q
apt-get install -y "$GTK_RT_PKG" libpam0g seatd libseat1 x11-xserver-utils xinit xterm
echo "  done."
echo

# ── Build or use prebuilt ─────────────────────────────────────────────────────
PREBUILT="xlogin-gtk${GTK_VERSION}"

if [ -f "$PREBUILT" ] && [ -f "xlogin-launcher" ] && [ -f "pam.d/xlogin" ]; then
    echo "Using prebuilt GTK${GTK_VERSION} binary ($PREBUILT)."
else
    echo "Building from source (GTK${GTK_VERSION})..."
    apt-get install -y "$GTK_DEV_PKG" libpam0g-dev build-essential gcc make
    make GTK_VERSION="$GTK_VERSION"
    echo "  build complete."
fi
echo

# ── Install binaries and config ───────────────────────────────────────────────
echo "Installing binaries and config..."
install -m 755 "$PREBUILT"     /usr/local/bin/xlogin
install -m 755 xlogin-launcher /usr/local/bin/
install -m 644 pam.d/xlogin    /etc/pam.d/
install -m 755 etc_init.d_xlogin-launcher /etc/init.d/xlogin-launcher
echo "  done."
echo

# ── Enable seatd at boot ──────────────────────────────────────────────────────
echo "Enabling seatd service..."
LC_ALL=C update-rc.d seatd defaults
echo "  done."
echo

# ── Target user ───────────────────────────────────────────────────────────────
read -p "Username to configure for graphical login: " TARGET_USER
if ! id "$TARGET_USER" > /dev/null 2>&1; then
    echo "ERROR: user '$TARGET_USER' does not exist." >&2
    exit 1
fi
USER_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)

echo "Adding $TARGET_USER to input and video groups..."
usermod -aG input,video "$TARGET_USER"
echo "  done."
echo

# ── Detect installed sessions ─────────────────────────────────────────────────
echo "Detecting installed sessions..."

SESSION_NAMES=()
SESSION_EXECS=()

if [ -d /usr/share/xsessions ]; then
    for desktop in /usr/share/xsessions/*.desktop; do
        [ -f "$desktop" ] || continue
        NAME=$(grep '^Name=' "$desktop" | head -1 | cut -d= -f2-)
        EXEC=$(grep '^Exec=' "$desktop" | head -1 | cut -d= -f2-)
        [ -z "$NAME" ] && continue
        [ -z "$EXEC" ] && continue
        SESSION_NAMES+=("$NAME")
        SESSION_EXECS+=("$EXEC")
    done
fi

CHOSEN_CMD=""

if [ ${#SESSION_NAMES[@]} -gt 0 ]; then
    echo "  Found:"
    for i in "${!SESSION_NAMES[@]}"; do
        echo "  $((i+1))) ${SESSION_NAMES[$i]}"
    done
    echo
    while true; do
        read -p "Enter number [1-${#SESSION_NAMES[@]}]: " CHOICE
        if [[ "$CHOICE" =~ ^[0-9]+$ ]] && \
           [ "$CHOICE" -ge 1 ] && [ "$CHOICE" -le "${#SESSION_NAMES[@]}" ]; then
            CHOSEN_CMD="${SESSION_EXECS[$((CHOICE-1))]}"
            break
        fi
        echo "  Invalid choice."
    done
else
    echo "  No sessions found in /usr/share/xsessions/."
    echo "  Install a window manager or desktop environment first, then re-run,"
    echo "  or enter a session command manually (leave blank to abort):"
    read -p "  Session command: " CHOSEN_CMD
    if [ -z "$CHOSEN_CMD" ]; then
        echo "ERROR: no session command provided." >&2
        exit 1
    fi
fi

echo "Using session command: $CHOSEN_CMD"
echo

# ── D-Bus session ─────────────────────────────────────────────────────────────
echo "Start the session inside a D-Bus session bus?"
echo "  Enables trash, removable media, and other GVfs-backed features"
echo "  in file managers such as pcmanfm. Uses dbus-run-session."
echo
read -p "Add dbus-run-session to ~/.xinitrc? [Y/n]: " DBUS_CHOICE
case "$DBUS_CHOICE" in
    [nN]*) USE_DBUS=no ;;
    *)     USE_DBUS=yes ;;
esac

if [ "$USE_DBUS" = "yes" ]; then
    if ! command -v dbus-run-session > /dev/null 2>&1; then
        echo "  Installing dbus..."
        apt-get install -y dbus
    fi
    SESSION_EXEC="dbus-run-session $CHOSEN_CMD"
else
    SESSION_EXEC="$CHOSEN_CMD"
fi
echo "  Session command: $SESSION_EXEC"
echo

# ── Write ~/.xinitrc ──────────────────────────────────────────────────────────
XINITRC="$USER_HOME/.xinitrc"
WRITE_XINITRC=yes

if [ -f "$XINITRC" ]; then
    echo "  $XINITRC already exists."
    read -p "  Overwrite it? [y/N]: " OW
    case "$OW" in
        [yY]*) WRITE_XINITRC=yes ;;
        *)     WRITE_XINITRC=no ;;
    esac
fi

if [ "$WRITE_XINITRC" = "yes" ]; then
    cat > "$XINITRC" <<EOF
#!/bin/sh
exec $SESSION_EXEC
EOF
    chown "$TARGET_USER:$TARGET_USER" "$XINITRC"
    chmod 755 "$XINITRC"
    echo "  Wrote $XINITRC"
fi

# Also install to /etc/skel so new users get a working .xinitrc
cat > /etc/skel/.xinitrc <<EOF
#!/bin/sh
exec $SESSION_EXEC
EOF
chmod 755 /etc/skel/.xinitrc
echo "  Wrote /etc/skel/.xinitrc"
echo

# ── Configure inittab ─────────────────────────────────────────────────────────
if ! grep -q xlogin-launcher /etc/inittab 2>/dev/null; then
    echo "Updating /etc/inittab..."
    cp /etc/inittab "/etc/inittab.backup.$(date +%Y%m%d_%H%M%S)"
    sed -i '/^1:[0-9]*:respawn:.*[ag]etty/s/^/#/' /etc/inittab
    echo "1:2345:respawn:/usr/local/bin/xlogin-launcher" >> /etc/inittab
    telinit q
    echo "  done."
else
    echo "inittab already configured."
fi
echo

echo "=== Installation complete ==="
echo
echo "Notes:"
echo "  - Reboot to activate the graphical login screen."
echo "    Logging out of a graphical session returns you to the current display"
echo "    manager, not xlogin. A full reboot is required."
echo "  - Users can customise their session by editing ~/.xinitrc"
echo "  - To add another user, re-run this script or manually:"
echo "      usermod -aG input,video <username>"
echo "      cp /etc/skel/.xinitrc /home/<username>/.xinitrc"
echo "      chown <username>:<username> /home/<username>/.xinitrc"
